title: Michał Michalski
email: buyuk.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for sharing thoughts, projects, and things I've learned about
  software engineering and other topics that I find interesting enough.

baseurl: ""
url: "https://buyuk-dev.github.io"
github_username:  buyuk-dev

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

navigation:
  - title: Resume
    url: "https://github.com/buyuk-dev/resume"

# Google Analytics
google_analytics: UA-144833176-1

# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
