name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_resume:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
            
      - name: Checkout latest resume markdown from my resume repository
        run: |
          # Download latest resume markdown file.
          bash scripts/update_resume.sh

          # Commit updated file to repo.
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"

          git add resume.md
          git commit -m "Update pdf version;" || echo "No changes to commit"
          git push
